### ISSUE TITLE
Source fresh zoning information from arcgis server

### ISSUE THREAD

**Issue by fgregg** [datamade/second-city-zoning#18]
We can get fresh zoning information from http://gisapps.cityofchicago.org/arcgis/rest/services/ExternalApps/Zoning/MapServer/1

Using https://github.com/datamade/pyesridump

**Comment by derekeder** [comment]
Trying this out now:

`esri2geojson http://gisapps.cityofchicago.org/arcgis/rest/services/ExternalApps/Zoning/MapServer/1 chicago-zoning.geojson`

Using this one https://github.com/openaddresses/pyesridump
