### ISSUE TITLE
Expired Link under Data Section

### ISSUE THREAD

**Issue by yueyue-w** [datamade/second-city-zoning#31]
Hello, 

Thank you for your hard work and contribution. This is an impressive and great tool!
I was wondering if it's possible for you to update the link that stores the latest version of the zoning boundary file. Thank you in advance.

The following link seems like expired and directed us to - '404 ERROR
We are sorry but it seems the page you're looking for doesn't exist.'

"Everyting is stored in CartoDB and CSV files and are open for anyone to use:
[Zoning districts map](https://datamade.carto.com/viz/371a8f63-ce3b-49d6-8feb-c194053227af/public_map)"

**Comment by derekeder** [comment]
fixed in 1377b4c5e71b1924d8e81dc4603a621a0addadda
