### ISSUE TITLE
Translation using r18n (getting started)

### ISSUE THREAD

**Issue by renemarcelo** [datamade/second-city-zoning#6]
Exposure Boost: spanish speakers interested in open data.  I'm not sure if I can use an es-us.yml file (United States Spanish)  or if I need create it ? Thanks.
![explorer_spanish](https://f.cloud.github.com/assets/1162669/174252/fb939954-7b00-11e2-9000-0ac9606c4214.png)

**Comment by derekeder** [comment]
@renemarcelo still interested in this? I think spanish language support would be a great addition!

These pages are probably good candidates for translation:

* http://secondcityzoning.org/about/
* http://secondcityzoning.org/zoning_rules/
* http://secondcityzoning.org/zones/

The zone detail pages (like (RS-1)[http://secondcityzoning.org/zone/RS-1/]) and the descriptions that show up in the map popups are derived from this spreadsheet: https://github.com/open-city/second-city-zoning/blob/master/resources/import/zoning-code-summary-district-types.csv. Translating the titles and descriptions in there may be a good place to start.
